server:
  port: 6666 # 定义自己项目启动端口
  servlet:
    context-path: /tog
spring:
  application:
    name: ${APP_NAME:TogBoot}
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, env, metrics # Actuator默认把所有访问点暴露给JMX，但处于安全原因，只有health和info会暴露给Web。